### ISSUE TITLE
Travis builds for python3.5 can't start

### ISSUE THREAD

**Issue by DanielPollithy** [Blueshoe/djangocms-reversion2#35]
Reference: [https://travis-ci.org/Blueshoe/djangocms-reversion2/builds/279460478](https://travis-ci.org/Blueshoe/djangocms-reversion2/builds/279460478)

@mammuth Have you seen this error before?

**Comment by mammuth** [comment]
I have not seen this before. But it looks like it's not even using Python 3.5 for the job (line 431):
```
$ python --version
Python 2.7.13
```

**Comment by DanielPollithy** [comment]
In line 455 it tried to use the tox py35-latest version.
`$ tox -e $TOX_ENV
GLOB sdist-make: /home/travis/build/Blueshoe/djangocms-reversion2/setup.py
py35-latest create: /home/travis/build/Blueshoe/djangocms-reversion2/.tox/py35-latest`

Using tox-pyenv in order to pin the versions seemed to work although it's rather nasty...

https://github.com/samstav/circleci-python-sandbox/issues/1
